#version of docker compose
version: "3"


services: 
  myapp:
  image: myimage:latest
  
  container_name: myimagecont
  hostname: splitter
  init: true
 # server: 
  #  container_name: server
  #path to docker file and it will build
  #build: .
 # dockerfile: Dockerfile
  ports: 
   - "9997:9997"
  expose:
    - "9997"



   



    